<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <title>Free Multipurpose Template : RUMA</title>
    <!-- BOOTSTRAP CORE STYLE CSS -->
    <link href="css/bootstrap.css" rel="stylesheet" />
    <!-- FONTAWESOME STYLE CSS -->
    <link href="css/font-awesome.min.css" rel="stylesheet" />
    <!-- CUSTOM STYLE CSS -->
    <link href="css/style.css" rel="stylesheet" />    
    <!-- GOOGLE FONT -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />

</head>
<body >
    
    
    <section id="footer-sec" >
             
            <div class="container">
           <div class="row  pad-bottom" >
            <div class="col-md-4">
                <h4> <strong class="fit">ABOUT ORGANIZATION</strong> </h4>
                <p id="abt"><b>
                               	 Sri Lanka Eye Donation Society is a silent institution doing a big role in serving the mankind by donating Human Corneas and Tissues to the needy patients any where in the world irrespective of them color, race, religion etc. This small developing country of 20 million people has become a source for corneas to thousands of blind persons on this earth and our services will be continued till the blindness is totally eradicated from the world, which is the main object of this society."
 
Sri Lanka Eye Donation Society is the mother body of ,
<ul>
    <li>International Eye Bank</li>

    <li>Human Tissue Bank</li>

    <li>	Dr.Hudson Silva Eye Hospital</li>

    <li>Contact Lens Lab</li>
</ul>
 

                    </b>  </p>
                <a href="#" >read more</a>
                </div>
               <div class="col-md-4 col-sm-4">
                    <h4> <strong></strong> </h4>
                    <image src="interface/images/logofooter.png" id="logof">
                </div>  
               <div id="founder" class="col-md-4 ">
                   <h4> <strong   class="fit">OUR FOUNDER</strong> </h4>
                   <image src="interface/images/doctor.jpg">
                       <p><b>
                              Deshabandu 
                              Lion <br>
                                  Dr. F.G. Hudson Silva M.J.F <br>
Founder of the 
Sri Lanka Eye Donation Society
</b></p>
                    
                </div>
               <div class="social">
                   <h4 id="fi" class="fit"> <strong>FIND US ON</strong> </h4><br><br>

                   <a href="#" target="_blank"><image src="interface/imgs/fb.png" class="social"></a>
                   <a href="#" target="_blank"><image src="interface/imgs/tw.png" class="social"></a>
                   <a href="#" target="_blank"><image src="interface/imgs/g.png" class="social"></a>
                    
                    
                </div>
               </div>
                
               
            </div>
       
         
    </section>     
     <div class="tagline">Powered by : Computer Society - University of Colombo School of Computing</div>
     <div class="end"></div>   
    
    <!--/.FOOTER END-->
    <!-- JAVASCRIPT FILES PLACED AT THE BOTTOM TO REDUCE THE LOADING TIME  -->
    <!-- CORE JQUERY  -->
    <script src="assets/plugins/jquery-1.10.2.js"></script>
    <!-- BOOTSTRAP SCRIPTS  -->
    <script src="assets/plugins/bootstrap.js"></script>
  <!-- CUSTOM SCRIPTS  -->
    <script src="assets/js/custom.js"></script>
</body>
</html>
