
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
                <!-- Header Links-->
		<title>SriLanka Eye Donation Society</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="css/styles.css" rel="stylesheet">
                
	</head>
        <body >
<nav class="navbar navbar-static" script>
    <a class="navbar-brand " href="http://localhost/netbeans/Eyee/index.php" target="ext"><b><image src="interface/images/eye.png"></b></a>
   <div class="container">
    <div class="navbar-header" >
      
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="glyphicon glyphicon-chevron-down"></span>
      </a>
    </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">  
            <li ><a href="#" class="active" >Home</a></li>
          <li><a href="surgeon.php">Surgeons</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Donate</a>
            <ul class="dropdown-menu">
              <li><a href="#">Cash</a></li>
              <li><a href="#">Tissues</a></li>
              
              
            </ul>
            <li><a href="#">Eyes</a></li>
            <li><a href="#">Tissues</a></li>
             <li><a href="#">Reservations</a></li>
            <li><a href="#">Lens Lab</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Contact Us</a></li>
          </li>
          
        </ul>
         <b id="topname">SriLanka Eye Donation Society</b>
        
      </div>
       
       
    </div>
    
    
                    
	
		
	</body>
</html>